### ISSUE TITLE
Do not add the special path that only exist in your device

### ISSUE THREAD

**Issue by lindexi** [MyScript/interactive-ink-examples-wpf#2]
The demo add the special path in csproj and which file only exist in your device 

https://github.com/MyScript/interactive-ink-examples-wpf/blob/f3e155e4ee68ec65fa3de154ae7ebb4152253230/GetStarted/MyScript.InteractiveInk.GetStarted.Wpf-VS2017.csproj#L114

Please delete it.

**Comment by MyScriptSupport** [comment]
Dear Lindexi,

Thank you for your comment. We added your remark, and will take it into account on future versions of the iink SDK.

Best regards,

Olivier
