### ISSUE TITLE
Is there an example of SDK1.5?

### ISSUE THREAD

**Issue by wang-yulong** [MyScript/interactive-ink-examples-wpf#3]
Because the framework of my program is 4.5.2.

Is there an example of SDK1.5? thank you

**Comment by Olivier-myscript** [comment]
Dear Wang-Yulong,

thank you for contacting us.

Ideally, we recommend you use the latest 2.0 release, which is up to date with our latest technology improvements.

The 1.5 can still be downloaded on gitub Ensure you get the 1.5.1 tag.

Best regards

Olivier
![1 5 1](https://user-images.githubusercontent.com/121610488/221511901-d5fa6328-d819-4ee0-a87c-fced11188ecc.png)
